Repository ACE-VSIT/website, pull requests merged in 2022-10, with the labels that each got.

#62 Timer for registrations page
  packages/common/src/exports.tsx
  packages/common/src/interfaces/IGetTimeRemaning.ts
  packages/common/src/utils/getTimeRemaining.ts
  packages/website/src/components/portal/components/TimeLine/Timeline.js
  packages/website/src/components/timer/Timer.js
  packages/website/src/pages/register.js
  packages/website/src/schemas/Questions.json
Labels: enhancement

#65 Add image-slider for /gallery
  packages/common/src/exports.tsx
  packages/website/src/components/Gallery/components/image-grid/ImageGrid.js
  packages/website/src/components/Gallery/components/image-grid/ImageGridElements.js
  packages/website/src/components/Gallery/components/image-slider/ImageSlider.js
  packages/website/src/components/Gallery/components/image-slider/ImageSliderElements.js
  packages/website/src/components/Gallery/index.js
Labels: enhancement

#66 Rollback admintable to bb67127
  packages/admintable/.eslintignore
  packages/admintable/.eslintrc.json
  packages/admintable/package.json
  packages/admintable/src/App.tsx
  packages/admintable/src/bootstrap.tsx
  packages/admintable/src/components/dashboard/DashboardElements.tsx
  packages/admintable/src/components/index-elements.styles.tsx
  packages/admintable/src/components/table/TableComponent.tsx
  packages/admintable/src/components/table/TableContainer.tsx
  packages/admintable/src/components/table/components/inputs/InputDate.tsx
  packages/admintable/src/components/table/components/inputs/InputImage.tsx
  packages/admintable/src/components/table/components/inputs/InputText.tsx
  packages/admintable/src/components/table/components/inputs/SelectOption.tsx
  packages/admintable/src/components/table/components/inputs/index.ts
  packages/admintable/src/components/table/components/inputs/styles/input.styles.tsx
  packages/admintable/src/components/table/components/inputs/styles/table-elements.styles.tsx
  packages/admintable/src/components/table/components/pagination/Pagination.tsx
  packages/admintable/src/components/table/components/toolbar/Toolbar.tsx
  packages/admintable/src/components/table/components/toolbar/filter/Filter.tsx
  packages/admintable/src/components/table/components/toolbar/filter/FilterMenu.tsx
  packages/admintable/src/components/table/components/updater/Updater.tsx
  packages/admintable/src/components/table/helpers/helper-functions.ts
  packages/admintable/src/components/toolbar/components/CellSize/CellSize.tsx
  packages/admintable/src/components/toolbar/components/CellSize/ICellSize.ts
  packages/admintable/src/components/toolbar/components/Filter/Filter.tsx
  packages/admintable/src/components/toolbar/components/Filter/IFilter.ts
  packages/admintable/src/components/toolbar/index.tsx
  packages/admintable/src/configs/navbar.config.ts
  packages/admintable/src/configs/user-table-config.ts
  packages/admintable/src/contexts/AuthContext.tsx
  packages/admintable/src/contexts/TableContext.tsx
  packages/admintable/src/contexts/ThemeContext.tsx
  packages/admintable/src/contexts/UserInfoContext.tsx
  packages/admintable/src/index.js
  packages/admintable/src/interfaces/input.interface.ts
  packages/admintable/src/interfaces/pagination.interface.ts
  packages/admintable/src/interfaces/user.interface.ts
  packages/admintable/src/pages/Dashboard.tsx
  packages/admintable/src/pages/Index.tsx
  packages/admintable/src/pages/NotFound.tsx
  packages/admintable/src/pages/SignOut.tsx
  packages/admintable/src/reportWebVitals.ts
  packages/admintable/src/setupTests.ts
  packages/admintable/src/theme/GlobalStyles.tsx
  packages/admintable/src/theme/theme.d.ts
  packages/admintable/src/utils/PrivateRoutes.tsx
  packages/admintable/src/utils/firebase.tsx
  packages/admintable/src/utils/functions.tsx
  packages/admintable/yarn.lock
Labels: bug

#67 Update README.md and DIRECTORY.md
  DIRECTORY.md
  README.md
Labels: documentation

#68 Admintable: Create Registrations Modal
  packages/admintable/package.json
  packages/admintable/src/App.tsx
  packages/admintable/src/components/table/TableComponent.tsx
  packages/admintable/src/components/table/components/inputs/InputText.tsx
  packages/admintable/src/components/table/components/registrations/RegistrationsButton.tsx
  packages/admintable/src/components/table/components/registrations/RegistrationsModal.tsx
  packages/admintable/src/components/table/components/updater/Updater.tsx
  packages/admintable/src/configs/registrations.config.ts
  packages/admintable/src/configs/user-table-config.ts
  packages/admintable/src/interfaces/input.interface.ts
  packages/admintable/src/interfaces/registrations.interface.ts
  packages/admintable/src/interfaces/user.interface.ts
  packages/admintable/src/theme/GlobalStyles.tsx
  packages/admintable/src/utils/functions.tsx
  yarn.lock
Labels: enhancement

#69 * added cross-env
  package.json
  packages/common/.eslintrc.json
  packages/common/package.json
  packages/functions/.eslintrc.json
  packages/website/.eslintrc.json
  yarn.lock
Labels: enhancement
